import test from 'node:test';
import assert from 'node:assert/strict';
import {writeFileSync} from 'node:fs';
import {generateChat} from '../cli/chat-generator.mjs';

function fake({out,code=0,wait=0,error}={}){return (_bin,args,options)=>{const h={};let input='';const child={stdin:{end(v){input=v;},on(){}},stdout:{on(){}},stderr:{on(){}},once(e,fn){h[e]=fn;},kill(){h.close?.(null,'SIGTERM');}};setTimeout(()=>{if(error)h.error?.(error);else{const p=args[args.indexOf('--output-last-message')+1];if(out!==undefined)writeFileSync(p,out);h.close?.(code,null);}},wait);child.input=()=>input;return child;};}
test('uses reply file, stdin prompt, and locked Luna flags',async()=>{let seen;const result=await generateChat({prompt:'說一句話',spawnImpl:(b,a,o)=>{seen={args:a,options:o};const c=fake({out:'{"text":"你好，旅人！"}'})(b,a,o);setTimeout(()=>{seen.input=c.input();},1);return c;}});assert.equal(result.text,'你好，旅人！');assert.equal(seen.args.at(-1),'-');assert.equal(seen.args[seen.args.indexOf('--model')+1],'gpt-5.6-luna');assert.ok(seen.args.includes('--output-last-message'));assert.equal(seen.options.shell,false);});
test('rejects invalid output, alternate model, and nonzero child',async()=>{await assert.rejects(generateChat({prompt:'x',spawnImpl:fake({out:'no'})}),e=>e.code==='GENERATION_FAILED');await assert.rejects(generateChat({prompt:'x',model:'gpt-5.6-astra',spawnImpl:fake({out:'{"text":"x"}'})}),e=>e.code==='MODEL_UNAVAILABLE');await assert.rejects(generateChat({prompt:'x',spawnImpl:fake({out:'{"text":"x"}',code:1})}),e=>e.code==='GENERATION_FAILED');});
test('maps timeout and unavailable child safely',async()=>{await assert.rejects(generateChat({prompt:'x',timeoutMs:10,spawnImpl:fake({wait:100})}),e=>e.code==='TIMEOUT');await assert.rejects(generateChat({prompt:'x',spawnImpl:fake({error:Object.assign(new Error('missing'),{code:'ENOENT'})})}),e=>e.code==='MODEL_UNAVAILABLE');});
test('pre-aborted generation does not spawn or leave a timer',async()=>{const controller=new AbortController();controller.abort();let spawned=false;await assert.rejects(generateChat({prompt:'x',signal:controller.signal,spawnImpl:()=>{spawned=true;}}),e=>e.code==='TIMEOUT');assert.equal(spawned,false);});
test('model can intentionally stay silent',async()=>{const result=await generateChat({prompt:'話題已結束',spawnImpl:fake({out:'{"text":""}'})});assert.equal(result.text,'');});
