import test from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {once} from 'node:events';
import {mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import path from 'node:path';
import {GameService} from '../server/service.mjs';
import {CommerceService} from '../server/commerce.mjs';
import {createApp} from '../server/index.mjs';
import {CloudClient} from '../cli/cloud-client.mjs';
const catalog={version:'test',items:{},skills:{},wrap:JSON.stringify,unwrap:JSON.parse};
const password='commerce-test-password-2026!';
const key='lineage_idle_save_1';
const doc=()=>({p:{cls:'elf',name:'藍鑽妖精',lv:1,exp:0,gold:1000,inv:[],base:{dex:20},_roleEpoch:randomUUID()},ticks:0});
async function fixture(t){
 const service=new GameService(':memory:',catalog),shop=new CommerceService(service);t.after(()=>service.close());
 const gm=await service.register('shop_gm',password,{initialGm:true}),player=await service.register('shop_player',password),other=await service.register('shop_other',password);
 const lease=randomUUID(),character=doc();service.acquireLease(player,lease);service.sync(player,lease,0,{[key]:catalog.wrap(character)});
 return {service,shop,gm,player,other,lease,character};
}
const credit=(shop,gm,player,amount)=>shop.grant(gm,{accountId:player.id,amount,reason:'測試儲值',requestId:randomUUID()});
const buy=(shop,user,productId)=>shop.buy(user,{productId,requestId:randomUUID()});
test('only GM credits diamonds, with exact integer amounts and durable idempotent audit',async t=>{
 const {service,shop,gm,player}=await fixture(t);
 const request={accountId:player.id,amount:3500,reason:'儲值單 001',requestId:randomUUID()};
 assert.throws(()=>shop.grant(player,request),e=>e.status===403);
 for(const amount of [-1,0,1.5,Infinity,'500'])assert.throws(()=>shop.grant(gm,{...request,amount}));
 shop.grant(gm,request);assert.equal(shop.grant(gm,request).replayed,true);
 assert.equal(shop.wallet(player.id).diamonds,3500);assert.equal(shop.history(player.id).length,1);
 assert.equal(shop.history(player.id)[0].actor,'shop_gm');
 assert.throws(()=>shop.grant(gm,{...request,amount:3501}),e=>e.status===409);
 service.db.prepare("UPDATE accounts SET role='player' WHERE id=?").run(gm.id);
 assert.throws(()=>shop.grant(gm,{...request,requestId:randomUUID()}),e=>e.status===403);
});
test('prices are server owned, retries cannot double charge and cards cannot overdraw',async t=>{
 const {service,shop,gm,player,other,lease}=await fixture(t);
 credit(shop,gm,player,3500);
 const purchase={productId:'rename_card',price:0,accountId:other.id,requestId:randomUUID()};
 shop.buy(player,purchase);shop.buy(player,purchase);buy(shop,player,'password_card');
 assert.deepEqual(shop.wallet(player.id),{diamonds:0,renameCards:1,passwordCards:1});
 assert.equal(shop.wallet(other.id).diamonds,0);
 assert.throws(()=>buy(shop,player,'password_card'),e=>e.status===409);
 const snapshot=service.bootstrap(player),forged=JSON.parse(snapshot.values[key]);forged.p.blueDiamonds=999999;forged.p.renameCards=99;
 service.sync(player,lease,snapshot.revision,{[key]:JSON.stringify(forged),lineage_blue_diamonds:'999999'},{slot:1,name:'冒名改名'});
  assert.deepEqual(shop.wallet(player.id),{diamonds:0,renameCards:1,passwordCards:1});
 assert.equal(service.online().find(p=>p.username===player.username).name,'藍鑽妖精');
});
test('one rename card changes only the selected owned role, rejects free rename and rolls back invalid requests',async t=>{
 const {service,shop,gm,player,other,lease,character}=await fixture(t);credit(shop,gm,player,3000);buy(shop,player,'rename_card');
 const before=service.bootstrap(player),request={slot:1,epoch:character.p._roleEpoch,name:'黑貓新名字',requestId:randomUUID()};
 assert.throws(()=>shop.rename(other,request));
 assert.throws(()=>shop.rename(player,{...request,epoch:randomUUID()}),e=>e.status===409);
 assert.throws(()=>shop.rename(player,{...request,name:'<script>'}));
 assert.equal(shop.wallet(player.id).renameCards,1);
 shop.rename(player,request);assert.equal(shop.rename(player,request).replayed,true);
 const updated=JSON.parse(service.bootstrap(player).values[key]);
 assert.deepEqual(updated,{...character,p:{...character.p,name:'黑貓新名字'}});
 assert.equal(shop.wallet(player.id).renameCards,0);
 assert.throws(()=>service.sync(player,lease,before.revision,{[key]:before.values[key]}),e=>e.status===409&&!!e.details.snapshot);
 assert.throws(()=>service.sync(player,lease,before.revision+1,{[key]:before.values[key]}),e=>e.status===409&&e.details.nameConflict===true);
 assert.throws(()=>shop.rename(player,{...request,name:'再改一次',requestId:randomUUID()}));
});
test('password card validates old password, consumes once, preserves saves and revokes every target session',async t=>{
 const {service,shop,gm,player,other,lease}=await fixture(t);credit(shop,gm,player,1000);buy(shop,player,'password_card');buy(shop,player,'password_card');
 const first=await service.login(player.username,password),second=await service.login(player.username,password),otherLogin=await service.login(other.username,password);
 const before=service.bootstrap(player),newPassword='changed-commerce-password-2026!';
 await assert.rejects(()=>shop.password(player,{currentPassword:'wrong',newPassword,requestId:randomUUID()}),e=>e.status===403);
 await assert.rejects(()=>shop.password(player,{currentPassword:password,newPassword:'short',requestId:randomUUID()}));
 assert.equal(shop.wallet(player.id).passwordCards,2);
 const results=await Promise.allSettled([1,2].map(()=>shop.password(player,{currentPassword:password,newPassword,requestId:randomUUID()})));
 assert.equal(results.filter(r=>r.status==='fulfilled').length,1);assert.equal(shop.wallet(player.id).passwordCards,1);
 for(const session of [first,second])assert.throws(()=>service.authenticate(session.session),e=>e.status===401);
 assert.equal(service.authenticate(otherLogin.session).id,other.id);
 await assert.rejects(()=>service.login(player.username,password));await service.login(player.username,newPassword);
 assert.deepEqual(service.bootstrap(player).values,before.values);assert.equal(service.bootstrap(player).revision,before.revision);
 assert.throws(()=>service.checkLease(player,lease),e=>e.status===423);
 const audit=JSON.stringify(service.db.prepare('SELECT * FROM commerce_operations').all())+JSON.stringify(shop.history(player.id));
 assert.ok(!audit.includes(password)&&!audit.includes(newPassword));
});
test('cloud rejects imported progression, identity replacement, duplicate and deleted character replay',async t=>{
 const {service,player,other,lease,character}=await fixture(t);const otherLease=randomUUID();service.acquireLease(other,otherLease);
 const advanced=doc();advanced.p.lv=90;
 assert.throws(()=>service.sync(other,otherLease,0,{[key]:JSON.stringify(advanced)}),e=>e.status===403);
 assert.throws(()=>service.sync(other,otherLease,0,{[key]:JSON.stringify(character)}),e=>e.status===403);
 assert.throws(()=>service.sync(player,lease,1,{lineage_idle_save_2:JSON.stringify(character)}),e=>e.status===403);
 assert.throws(()=>service.sync(player,lease,1,{[key]:JSON.stringify(doc())}),e=>e.status===403);
 const differentClass=structuredClone(character);differentClass.p.cls='mage';
 assert.throws(()=>service.sync(player,lease,1,{[key]:JSON.stringify(differentClass)}),e=>e.status===403);
 service.sync(player,lease,1,{[key]:null});
 assert.throws(()=>service.sync(player,lease,2,{[key]:JSON.stringify(character)}),e=>e.status===403);
 service.sync(player,lease,2,{[key]:JSON.stringify(doc())});assert.equal(service.bootstrap(player).revision,3);
});
test('wallets and character replay protection survive restart with existing saves',async t=>{
 const dir=mkdtempSync(path.join(tmpdir(),'blackcat-commerce-'));
 const filename=path.join(dir,'game.sqlite');let service=new GameService(filename,catalog),shop=new CommerceService(service);
 const gm=await service.register('persist_gm',password,{initialGm:true}),player=await service.register('persist_player',password),lease=randomUUID(),character=doc();
 service.acquireLease(player,lease);service.sync(player,lease,0,{[key]:JSON.stringify(character)});credit(shop,gm,player,3500);buy(shop,player,'rename_card');service.close();
 service=new GameService(filename,catalog);shop=new CommerceService(service);t.after(()=>{service.close();rmSync(dir,{recursive:true,force:true});});
 assert.deepEqual(shop.wallet(player.id),{diamonds:500,renameCards:1,passwordCards:0});assert.equal(shop.history(player.id).length,2);
 service.sync(player,lease,1,{[key]:null});assert.throws(()=>service.sync(player,lease,2,{[key]:JSON.stringify(character)}),e=>e.status===403);
});
test('HTTP protects GM credit and purchases with authentication/CSRF and exports read-only own-character reports',async t=>{
 const app=createApp({database:':memory:',catalog,publicOrigin:'',publicAliases:[]});app.server.listen(0,'127.0.0.1');await once(app.server,'listening');
 t.after(async()=>{app.server.closeAllConnections();await new Promise(resolve=>app.server.close(resolve));});
 const base=`http://127.0.0.1:${app.server.address().port}`,client=new CloudClient({baseUrl:base});
 const gm=await app.service.register('http_gm',password,{initialGm:true});const {user}=await client.register('http_player',password),session=client.exportSession(),lease=randomUUID();
 await client.acquireLease(lease);app.service.sync(user,lease,0,{[key]:JSON.stringify(doc())});
 const request=async(url,body,csrf=session.csrf)=>fetch(base+url,{method:body?'POST':'GET',headers:{Cookie:session.cookie,Origin:base,'Content-Type':'application/json','X-CSRF-Token':csrf},body:body?JSON.stringify(body):undefined});
 assert.equal((await fetch(base+'/api/shop')).status,401);
 assert.equal((await request('/api/gm/diamonds',{accountId:user.id,amount:3500,reason:'越權',requestId:randomUUID()})).status,403);
 assert.equal((await request('/api/shop/buy',{productId:'rename_card',requestId:randomUUID()},'bad')).status,403);
 credit(app.commerce,gm,user,3500);
 assert.equal((await request('/api/shop/buy',{productId:'rename_card',requestId:randomUUID()})).status,200);
 const report=await(await request('/api/character-report?slot=1')).json();assert.equal(report.readOnly,true);assert.equal(report.account,'http_player');assert.equal(report.p,undefined);
 assert.equal((await request('/api/character-report?slot=2')).status,404);
 assert.equal((await request('/api/import',report)).status,404);
});
