'use strict';
window.initMonsterAdmin=function({api,notify}){
  const $=id=>document.getElementById(id),make=(tag,text,cls)=>{const e=document.createElement(tag);if(text!=null)e.textContent=text;if(cls)e.className=cls;return e;};
  let data=null,all=[],page=1,selected=new Set(),editing=[],pending=null,proposal=null;
  const run=async fn=>{try{await fn();}catch(e){notify(e.message,true);}};
  $('view-monsters').innerHTML=`<section class="surface"><div class="section-heading"><h2>怪物強度快速調節</h2><button id="monsters-refresh" class="secondary small">重新整理</button></div>
    <p class="hint">套用到新生成的怪物，包含副本及變身階段。正在交戰的怪物保留目前狀態。倍率調整 HP、物理與魔法傷害；經驗、金幣和掉落倍率另行管理。個別倍率 × 全服倍率；HP 上限一億、傷害骰面／附加傷害上限一百萬，骰數保留。</p>
    <form id="monster-global-form"><div class="world-fields"><label>全服強度倍率<input id="monster-global-strength" type="number" min="0.1" max="20" step="0.1" value="1" required></label><label>修改原因<input id="monster-global-reason" minlength="2" maxlength="200" required placeholder="例如：週末頭目挑戰"></label></div><div class="monster-actions"><button type="button" class="secondary" data-strength="0.5">簡單 ×0.5</button><button type="button" class="secondary" data-strength="1">標準 ×1</button><button type="button" class="secondary" data-strength="2">困難 ×2</button><button type="button" class="secondary" data-strength="5">極限 ×5</button><button class="primary">預覽全服調整</button></div></form></section>
    <section class="surface world-section"><h2>擊殺跑馬燈</h2><form id="monster-broadcast-form"><label class="world-check"><input id="monster-broadcast-enabled" type="checkbox">啟用擊殺跑馬燈及聊天室捷報</label><p class="hint">在下方選擇怪物，按「設定選取怪物」即可開關個別怪物的擊殺廣播。支援頭目與一般怪物；多階段頭目只在最終擊敗時廣播。訊息含角色名稱、怪物、地圖與台灣時間，不顯示帳號。關閉期間不補播。</p><p id="monster-broadcast-summary" class="hint"></p><label>修改原因<input id="monster-broadcast-reason" minlength="2" maxlength="200" required></label><button class="primary">儲存擊殺廣播開關</button></form></section>
    <section class="surface world-section" id="monster-browser"><div class="section-heading"><h2>全部怪物資料</h2><span id="monster-summary" role="status"></span></div><div class="world-fields"><label>搜尋名稱、ID 或種族<input id="monster-search" placeholder="例如：吉爾塔斯、哥布林"></label><label>所在地圖<select id="monster-map"><option value="">所有地圖</option></select></label><label class="world-check"><input id="monster-boss-only" type="checkbox">只看頭目</label><label class="world-check"><input id="monster-modified-only" type="checkbox">只看已調整</label></div><div class="monster-actions"><button id="monster-select-filtered" class="secondary">全選篩選結果</button><button id="monster-select-none" class="secondary">清除選取</button><button id="monster-edit-selected" class="primary" disabled>設定選取怪物（0）</button></div><div class="table-scroll"><table class="monster-table"><thead><tr><th>選取</th><th>怪物</th><th>等級</th><th>HP</th><th>物理傷害</th><th>AC / MR</th><th>攻擊間隔</th><th>重生間隔</th><th>擊殺廣播</th><th>管理</th></tr></thead><tbody id="monster-list"></tbody></table></div><div class="world-pagination"><button id="monster-prev" class="secondary">上一頁</button><span id="monster-page"></span><button id="monster-next" class="secondary">下一頁</button></div></section>
    <section class="surface world-section" id="monster-editor" hidden><div class="section-heading"><h2 id="monster-editor-title"></h2><button id="monster-editor-close" class="secondary">關閉編輯</button></div><p id="monster-editor-names" class="hint"></p><p class="hint">只套用勾選的欄位，其餘保留。數值為倍率前設定，席琳等場上效果另計。AC 越低、攻擊間隔越短，怪物越強。技能冷卻以 tick 計，1 tick = 0.1 秒。機率 0～1 代表 0%～100%。批次僅列出所有選取怪物共用的數值欄位。</p><form id="monster-edit-form"><div class="monster-editor-options"><label class="world-check"><input id="monster-change-strength" type="checkbox">調整個別強度倍率<input aria-label="個別強度倍率" id="monster-edit-strength" type="number" min="0.1" max="20" step="0.1" value="1"></label><label class="world-check"><input id="monster-change-broadcast" type="checkbox">調整擊殺廣播<select id="monster-edit-broadcast" aria-label="選取怪物擊殺廣播"><option value="true">開啟</option><option value="false">關閉</option></select></label></div><fieldset class="monster-respawn-settings"><legend>怪物重生時間</legend><label class="world-check"><input id="monster-change-respawn" type="checkbox">調整重生間隔</label><div class="world-fields"><label>重生規則<select id="monster-respawn-mode"><option value="custom">自訂間隔</option><option value="default">恢復原本規則</option></select></label><label>間隔時間<input id="monster-respawn-value" type="number" min="1" max="604800" step="1" value="5"></label><label>時間單位<select id="monster-respawn-unit"><option value="1">秒</option><option value="60">分鐘</option><option value="3600">小時</option></select></label></div><p class="hint">1 秒～7 天，從擊敗怪物起計時，依各角色的戰場分別計算。首次遭遇沿用原本規則；固定 BOSS 房等待冷卻，野外與裂痕冷卻結束後仍依原出現機率抽選。換圖、回村、重新登入及伺服器重啟不會清除冷卻。等待中的冷卻會依新設定重新計算，已在場的怪物保留。</p><p class="hint">多階段 BOSS 會同步修改整條變身鏈，最終擊敗後才計時；雙 BOSS 房會等兩隻都可重生後一起出現。副本進度、每日次數與入場需求仍須符合。</p><p id="monster-respawn-summary" class="hint"></p></fieldset><div id="monster-fields" class="monster-fields"></div><label>修改原因<input id="monster-edit-reason" minlength="2" maxlength="200" required></label><div class="monster-actions"><button class="primary">預覽怪物調整</button><button id="monster-reset" type="button" class="secondary">恢復選取怪物原始能力</button></div></form><div id="monster-full-data"></div></section>`;
  $('view-announcements').innerHTML=`<section class="surface"><div class="section-heading"><h2>GM 文字廣播</h2><button id="announcement-refresh" class="secondary">重新整理</button></div><p class="hint">全服同時顯示一則 GM 公告，新公告會替換舊公告。置頂公告固定文字並自動換行；未置頂時循環跑馬燈，直到設定時間結束。兩者都顯示在冒險區上方，不會被掉寶與擊殺訊息推走。</p><p id="announcement-current" class="hint" role="status"></p><form id="announcement-form"><label>廣播內容<textarea id="announcement-text" maxlength="300" rows="4" required placeholder="輸入要向全服玩家廣播的內容"></textarea></label><div class="world-fields"><label>持續時間<input id="announcement-duration" type="number" min="1" max="604800" step="1" value="10" required></label><label>時間單位<select id="announcement-unit"><option value="1">秒</option><option value="60" selected>分鐘</option><option value="3600">小時</option><option value="86400">天</option></select></label><label class="world-check"><input id="announcement-pinned" type="checkbox" checked>置頂固定顯示</label></div><p class="hint">最短 10 秒、最長 7 天，依伺服器時間自動結束。玩家約 4 秒收到更新；重新登入仍可看到尚未到期的公告。</p><label>操作原因<input id="announcement-reason" minlength="2" maxlength="200" required></label><div id="announcement-preview" class="announcement-preview" aria-label="公告預覽">GM 公告預覽</div><div class="monster-actions"><button class="primary">預覽並發布廣播</button><button id="announcement-stop" type="button" class="secondary">提前關閉目前廣播</button></div></form></section>`;
  const dialog=make('dialog');dialog.id='monster-confirm';dialog.innerHTML='<h2 id="monster-confirm-title"></h2><pre id="monster-confirm-detail"></pre><p id="monster-confirm-error" class="error" role="alert"></p><div class="dialog-actions"><button id="monster-confirm-cancel" class="secondary">取消</button><button id="monster-confirm-save" class="primary">確認套用</button></div>';document.body.append(dialog);
  function preview(command,title,detail){proposal=command;pending=null;$('monster-confirm-title').textContent=title;$('monster-confirm-detail').textContent=detail;$('monster-confirm-error').textContent='';dialog.showModal();}
  async function save(){
    const button=$('monster-confirm-save');button.disabled=true;
    try{pending||={...proposal,revision:data.revision,requestId:crypto.randomUUID()};await api('/api/gm/world-settings',pending);pending=null;dialog.close();notify('設定已儲存。');await load();if(editing.length)edit(editing.map(m=>m.id));}
    catch(e){$('monster-confirm-error').textContent=e.message+(e.status===409?'；請關閉預覽並重新整理設定。':'；可以重試，同一操作不會重複套用。');}
    finally{button.disabled=false;}
  }
  async function load(){
    data=await api('/api/gm/monsters?all=1');all=data.rows;
    $('monster-global-strength').value=data.strength;$('monster-broadcast-enabled').checked=data.broadcast.enabled;
    $('monster-broadcast-summary').textContent=`已設定 ${data.broadcast.monsters.length} 種怪物 · 廣播${data.broadcast.enabled?'已開啟':'已關閉'} · 設定版本 ${data.revision}`;
    const currentMap=$('monster-map').value;$('monster-map').replaceChildren(new Option('所有地圖',''));for(const m of data.maps)$('monster-map').append(new Option(m.name,m.id));$('monster-map').value=currentMap;
    const announcement=data.announcement,active=announcement&&announcement.expiresAt>Date.now();
    $('announcement-current').textContent=active?`目前${announcement.pinned?'置頂':'跑馬燈'}：${announcement.text}（至 ${new Date(announcement.expiresAt).toLocaleString('zh-TW')}）`:'目前沒有生效中的 GM 廣播。';$('announcement-stop').disabled=!active;
    selected=new Set([...selected].filter(id=>all.some(m=>m.id===id)));render();
  }
  const duration=seconds=>seconds==null?'原本規則':seconds%3600===0?(seconds/3600)+' 小時':seconds%60===0?(seconds/60)+' 分鐘':seconds+' 秒';
  const filtered=()=>{const q=$('monster-search').value.trim().toLowerCase(),map=$('monster-map').value;return all.filter(m=>(!q||(m.name+' '+m.id+' '+m.data.race).toLowerCase().includes(q))&&(!$('monster-boss-only').checked||m.boss)&&(!$('monster-modified-only').checked||Object.keys(m.rule).length)&&(!map||m.maps.some(p=>p.id===map)));};
  function selection(){const count=selected.size;$('monster-edit-selected').textContent=`設定選取怪物（${count}）`;$('monster-edit-selected').disabled=!count;}
  function render(){
    const rows=filtered(),pages=Math.max(1,Math.ceil(rows.length/40));page=Math.min(page,pages);$('monster-summary').textContent=`${rows.length} / ${all.length} 種`;$('monster-list').replaceChildren();selection();
    for(const m of rows.slice((page-1)*40,page*40)){
      const tr=make('tr'),checkCell=make('td'),check=make('input');check.type='checkbox';check.checked=selected.has(m.id);check.setAttribute('aria-label','選取 '+m.name+' '+m.id);check.onchange=()=>{if(check.checked)selected.add(m.id);else selected.delete(m.id);selection();};checkCell.append(check);
      const name=make('td',m.name+(m.boss?' · 頭目':''));name.append(make('small',m.id,'world-sub'));if(Object.keys(m.rule).length)name.append(make('small','已調整','world-changed'));
      const d=m.effective,cell=make('td'),button=make('button','資料／調整','secondary small');button.onclick=()=>edit([m.id]);cell.append(button);
      tr.append(checkCell,name,make('td',d.lv),make('td',Number(d.hp).toLocaleString()),make('td',(d.dmg||[0,0]).join('D')+' + '+(d.db||0)),make('td',`${d.ac??0} / ${d.mr??0}`),make('td',`${d.atkSpd??1} 秒`),make('td',duration(m.rule.respawnSeconds)),make('td',m.broadcast?'已勾選':'關閉'),cell);$('monster-list').append(tr);
    }
    $('monster-page').textContent=`${page} / ${pages}`;$('monster-prev').disabled=page<=1;$('monster-next').disabled=page>=pages;
  }
  function edit(ids){
    editing=all.filter(m=>ids.includes(m.id));if(!editing.length)return;
    $('monster-editor').hidden=false;$('monster-editor-title').textContent=editing.length===1?editing[0].name+' · 個別設定':`批次設定 ${editing.length} 種怪物`;$('monster-editor-names').textContent=editing.map(m=>m.name).join('、');
    $('monster-change-strength').checked=$('monster-change-broadcast').checked=false;$('monster-edit-strength').value=editing.length===1?(editing[0].rule.strength??1):1;$('monster-edit-broadcast').value=editing.length===1?String(editing[0].broadcast):'true';
    $('monster-change-respawn').checked=false;$('monster-respawn-mode').value='custom';
    const seconds=editing.length===1?(editing[0].rule.respawnSeconds??5):5,unit=seconds%3600===0?3600:seconds%60===0?60:1;
    $('monster-respawn-value').value=seconds/unit;$('monster-respawn-unit').value=String(unit);respawnMode();
    const familyIds=new Set(editing.flatMap(m=>m.respawnFamily||[m.id]));
    $('monster-respawn-summary').textContent='同步套用對象：'+all.filter(m=>familyIds.has(m.id)).map(m=>m.name).join('、')+(editing.length===1?'；目前：'+duration(editing[0].rule.respawnSeconds):'');
    $('monster-fields').replaceChildren();
    for(const field of editing[0].fields.filter(f=>editing.every(m=>m.fields.some(other=>other.path===f.path)))){
      const label=make('label',null,'monster-field'),check=make('input'),value=make('input');check.type='checkbox';check.dataset.field=field.path;check.setAttribute('aria-label','套用 '+field.label);value.type='number';value.min=Math.max(...editing.map(m=>m.fields.find(f=>f.path===field.path).min));value.max=Math.min(...editing.map(m=>m.fields.find(f=>f.path===field.path).max));value.step=field.step;value.value=editing[0].rule.values?.[field.path]??field.value;value.dataset.value=field.path;value.setAttribute('aria-label',field.label);value.oninput=()=>{check.checked=true;};label.append(check,make('span',field.label),value);$('monster-fields').append(label);
    }
    $('monster-full-data').replaceChildren();if(editing.length===1){const m=editing[0],details=make('details'),summary=make('summary','完整資料：原始數值、目前效果、技能、屬性與出沒地圖'),pre=make('pre',JSON.stringify({id:m.id,maps:m.maps,original:m.data,overrides:m.rule,effective:m.effective},null,2));details.append(summary,pre);$('monster-full-data').append(details);}
    $('monster-editor').scrollIntoView({block:'start',behavior:'smooth'});
  }
  function respawnMode(){const disabled=$('monster-respawn-mode').value==='default';$('monster-respawn-value').disabled=$('monster-respawn-unit').disabled=disabled;}
  for(const id of ['monster-respawn-mode','monster-respawn-value','monster-respawn-unit'])$(id).oninput=()=>{$('monster-change-respawn').checked=true;respawnMode();};
  $('monster-editor-close').onclick=()=>{$('monster-editor').hidden=true;editing=[];};
  $('monster-edit-selected').onclick=()=>edit([...selected]);$('monster-select-filtered').onclick=()=>{for(const m of filtered())selected.add(m.id);render();};$('monster-select-none').onclick=()=>{selected.clear();render();};
  for(const id of ['monster-search','monster-map','monster-boss-only','monster-modified-only'])$(id).oninput=()=>{page=1;render();};
  $('monster-prev').onclick=()=>{page--;render();};$('monster-next').onclick=()=>{page++;render();};
  $('monster-edit-form').noValidate=true;
  $('monster-edit-form').onsubmit=e=>{e.preventDefault();if(!$('monster-edit-reason').reportValidity())return;const values={};for(const check of $('monster-fields').querySelectorAll('[data-field]:checked')){const input=[...$('monster-fields').querySelectorAll('[data-value]')].find(el=>el.dataset.value===check.dataset.field);input.required=true;if(!input.reportValidity())return;values[check.dataset.field]=Number(input.value);}
    const command={type:'monsters',ids:editing.map(m=>m.id),values,reason:$('monster-edit-reason').value};if($('monster-change-strength').checked)command.strength=Number($('monster-edit-strength').value);if($('monster-change-broadcast').checked)command.broadcast=$('monster-edit-broadcast').value==='true';
    if(command.strength!==undefined){$('monster-edit-strength').required=true;if(!$('monster-edit-strength').reportValidity())return;}
    if($('monster-change-respawn').checked){
      command.respawnSeconds=null;
      if($('monster-respawn-mode').value==='custom'){
        const input=$('monster-respawn-value');input.required=true;if(!input.reportValidity())return;
        const seconds=Number(input.value)*Number($('monster-respawn-unit').value);
        if(!Number.isInteger(seconds)||seconds<1||seconds>604800){notify('重生間隔須為 1 秒～7 天。',true);return;}command.respawnSeconds=seconds;
      }
    }
    if(!Object.keys(values).length&&command.strength===undefined&&command.broadcast===undefined&&command.respawnSeconds===undefined){notify('請勾選要修改的項目。',true);return;}
    preview(command,`調整 ${editing.length} 種怪物`,editing.map(m=>m.name).join('、')+'\n\n'+JSON.stringify({能力:values,個別倍率:command.strength,擊殺廣播:command.broadcast,重生間隔:command.respawnSeconds===undefined?undefined:duration(command.respawnSeconds),重生同步對象:command.respawnSeconds===undefined?undefined:$('monster-respawn-summary').textContent},null,2));};
  $('monster-reset').onclick=()=>{if(!$('monster-edit-reason').reportValidity())return;preview({type:'monsters',ids:editing.map(m=>m.id),reset:true,reason:$('monster-edit-reason').value},'恢復原始能力',`清除 ${editing.length} 種怪物的個別能力與倍率調整；仍套用全服倍率，擊殺廣播與重生間隔設定保留。\n`+editing.map(m=>m.name).join('、'));};
  for(const button of document.querySelectorAll('[data-strength]'))button.onclick=()=>{$('monster-global-strength').value=button.dataset.strength;};
  $('monster-global-form').onsubmit=e=>{e.preventDefault();preview({type:'monster-strength',strength:Number($('monster-global-strength').value),reason:$('monster-global-reason').value},'全服怪物強度調整',`全部新生成怪物的 HP 與傷害 ×${$('monster-global-strength').value}。經驗、金幣與掉落倍率維持既有設定。`);};
  $('monster-broadcast-form').onsubmit=e=>{e.preventDefault();preview({type:'kill-broadcast',enabled:$('monster-broadcast-enabled').checked,monsters:data.broadcast.monsters,reason:$('monster-broadcast-reason').value},'擊殺廣播開關',`${$('monster-broadcast-enabled').checked?'開啟':'關閉'}廣播，目前勾選 ${data.broadcast.monsters.length} 種怪物。`);};
  $('announcement-text').oninput=()=>{$('announcement-preview').textContent='GM 公告｜'+$('announcement-text').value;};
  $('announcement-form').onsubmit=e=>{e.preventDefault();const command={type:'announcement',text:$('announcement-text').value,pinned:$('announcement-pinned').checked,seconds:Number($('announcement-duration').value)*Number($('announcement-unit').value),reason:$('announcement-reason').value};if(command.seconds<10||command.seconds>604800){notify('廣播時間須為 10 秒～7 天。',true);return;}preview(command,'發布 GM 廣播',`${command.pinned?'置頂固定顯示':'循環跑馬燈'} · ${command.seconds} 秒\n\n${command.text}`);};
  $('announcement-stop').onclick=()=>{if(!$('announcement-reason').reportValidity())return;preview({type:'announcement-clear',reason:$('announcement-reason').value},'提前關閉 GM 廣播',data.announcement?.text||'目前沒有公告');};
  $('monster-confirm-cancel').onclick=()=>dialog.close();$('monster-confirm-save').onclick=save;
  $('monsters-refresh').onclick=$('announcement-refresh').onclick=()=>{pending=null;run(load);};
  document.addEventListener('gm:view-change',e=>{if(['monsters','announcements'].includes(e.detail.view))run(load);});
};
